"""Add `time_entries.source`.

One nullable column with no server default, which is the only shape SQLite adds
**in place**. Anything else — NOT NULL, a non-constant default, a changed
constraint — sends the batch context down the rebuild path, and a rebuild of
this table is a `DROP` of every session in the database.

Verified rather than assumed: the rootpage of every table reads the same either
side of this upgrade, and the check itself was confirmed against a table that
was rebuilt on purpose — a coincidence would otherwise read as proof.


Revision ID: 2a1c5f96f406
Revises: 8935fb71dc8a
Create Date: 2026-08-21 00:00:39.416700

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a1c5f96f406'
down_revision: Union[str, Sequence[str], None] = '8935fb71dc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
