"""cap question prompt length

Revision ID: 5a4a8d8db041
Revises: 673aa7b0d638
Create Date: 2026-08-11 19:57:42.551281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4a8d8db041'
down_revision: Union[str, Sequence[str], None] = '673aa7b0d638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Narrow the prompt column to the length the questionnaire reserves space for.

    Existing prompts are left as they are: SQLite does not enforce a VARCHAR
    length, so nothing is truncated. The declaration matters for the next
    autogenerate, and for any database that would enforce it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Widen the prompt column again."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
