"""Add the pomodoros table.

A new table and nothing else, so none of the rebuild hazard applies: no existing
table is touched, and `batch_alter_table` here only attaches indexes to the
table this migration just created. Confirm with `sqlite_master.rootpage` either
side if in doubt — every pre-existing table should be unmoved.

The table carries no foreign key to `projects`. Pomodoro time reaches the tracker
only as an explicit copy, so there is deliberately nothing linking a pomodoro to
the session it produced.

Revision ID: 8935fb71dc8a
Revises: fd4f23387b28
Create Date: 2026-08-20 22:15:47.266220

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8935fb71dc8a"
down_revision: Union[str, Sequence[str], None] = "fd4f23387b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pomodoros",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("utc_offset", sa.Integer(), nullable=False),
        sa.Column("focus_seconds", sa.Integer(), nullable=False),
        sa.Column("break_seconds", sa.Integer(), nullable=False),
        sa.Column("tainted", sa.Boolean(), nullable=False),
        sa.Column("transferred_at", sa.DateTime(), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("client_updated_at", sa.DateTime(), nullable=True),
        sa.Column("server_received_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("break_seconds >= 0", name="ck_pomodoro_break_not_negative"),
        sa.CheckConstraint(
            "ended_at is null or ended_at > started_at",
            name="ck_pomodoro_ends_after_start",
        ),
        sa.CheckConstraint("focus_seconds > 0", name="ck_pomodoro_has_focus"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pomodoros", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pomodoros_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_pomodoros_user_started", ["user_id", "started_at"], unique=False
        )
        batch_op.create_index(
            "uq_pomodoro_client_id",
            ["user_id", "client_id"],
            unique=True,
            sqlite_where=sa.text("client_id IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pomodoros", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_pomodoro_client_id", sqlite_where=sa.text("client_id IS NOT NULL")
        )
        batch_op.drop_index("ix_pomodoros_user_started")
        batch_op.drop_index(batch_op.f("ix_pomodoros_user_id"))

    op.drop_table("pomodoros")
    # ### end Alembic commands ###
