"""updated_at on the tables the change digest reads

Revision ID: 8a23e0d33960
Revises: c72e9b41a8d5
Create Date: 2026-08-17

One nullable column on each of the six tables that lacked one, so that
``GET /api/changes`` can report *when* a collection last moved and not only how
many rows it holds. A count sees rows arriving and leaving; without a timestamp
an edit in place — renaming a project, widening a deduction band — is invisible
to another device until something else changes.

**Nullable, and with no server default, on purpose.** SQLite will not add a
``NOT NULL DEFAULT (CURRENT_TIMESTAMP)`` column to an existing table: it
requires a constant default, so Alembic falls back to rebuilding the table —
copy, ``DROP``, rename. That is the operation `env.py` disables foreign keys
for, and the one that once emptied every answer and option in this database. An
autogenerated first draft of this migration did exactly that to all six tables;
comparing ``sqlite_master.rootpage`` either side proved it, and comparing it
again proved this version does not. A plain ``ALTER TABLE ... ADD COLUMN`` is
the one shape of change SQLite performs in place.

Existing rows therefore read NULL, which is precisely what the digest already
handles: a collection whose newest timestamp is NULL is compared on its count
alone, exactly as all six were before this migration. The first write to any row
fills its own timestamp in, and edit detection begins there. Nothing is
backfilled, because a backfill would claim every row changed at the moment of
deployment.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8a23e0d33960"
down_revision: str | Sequence[str] | None = "c72e9b41a8d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STAMPED = ("catalogues", "deduction_bands", "projects", "questions", "tags", "users")
"""The tables gaining a timestamp. `answers` and `time_entries` already had one."""


def upgrade() -> None:
    """Add a nullable ``updated_at`` to each table that lacked one."""
    for table in STAMPED:
        with op.batch_alter_table(table) as batch:
            batch.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Remove the timestamps again, leaving the digest to compare counts."""
    for table in reversed(STAMPED):
        with op.batch_alter_table(table) as batch:
            batch.drop_column("updated_at")
