"""computed scores

Revision ID: a4d14db0fd08
Revises: 5a4a8d8db041
Create Date: 2026-08-12 13:31:27.899266

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4d14db0fd08'
down_revision: Union[str, Sequence[str], None] = '5a4a8d8db041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add score definitions, and say explicitly where a question comes from."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_question_id', sa.Integer(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['score_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_question_id', 'source_question_id', name='uq_score_component')
    )
    with op.batch_alter_table('score_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_components_score_question_id'), ['score_question_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=16), server_default='asked', nullable=False))
        batch_op.add_column(sa.Column('aggregate', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('require_all', sa.Boolean(), server_default='1', nullable=False))

    # The auto-tracked questions are exactly those that carried a system_key,
    # which is what the flag used to mean.
    op.execute(
        sa.text("UPDATE questions SET origin = 'auto' WHERE system_key IS NOT NULL")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop score definitions and the origin column."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('require_all')
        batch_op.drop_column('aggregate')
        batch_op.drop_column('origin')

    with op.batch_alter_table('score_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_components_score_question_id'))

    op.drop_table('score_components')
    # ### end Alembic commands ###
