"""A second factor at login

Revision ID: c72e9b41a8d5
Revises: b1c4e7a90d21
Create Date: 2026-08-16

Three nullable columns on ``users`` and nothing else. Every existing account
gets NULL in all three, which reads as "never enrolled" — so this migration
changes nobody's ability to log in, which is the property that matters most for
a change to the authentication path.

Written by hand rather than autogenerated, and worth saying why: `env.py` sets
``render_as_batch``, so altering this table rewrites it — copy, ``DROP``,
rename. That ``DROP`` has cascaded and emptied tables in this database before.
Adding a **nullable column with no default** is the shape SQLite performs in
place, so the batch context here issues a plain ``ALTER TABLE ... ADD COLUMN``
and never rebuilds the table. All three columns below are exactly that.
`tests/test_migrations.py` walks the chain and fails if any revision loses a row.

That qualification is not pedantry, and this docstring used to omit it: adding a
``NOT NULL`` column *with* a default sends the same batch context down the
rebuild path instead, which revision ``8a23e0d33960`` ran into and had to be
rewritten to avoid. "Adding columns is safe" is the wrong rule; "adding nullable
columns with no default is safe" is the right one.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c72e9b41a8d5"
down_revision: str | Sequence[str] | None = "b1c4e7a90d21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the TOTP secret, its confirmation stamp and the replay guard."""
    with op.batch_alter_table("users") as batch:
        batch.add_column(sa.Column("totp_secret", sa.String(length=255), nullable=True))
        batch.add_column(sa.Column("totp_confirmed_at", sa.DateTime(), nullable=True))
        batch.add_column(sa.Column("totp_last_step", sa.Integer(), nullable=True))


def downgrade() -> None:
    """Remove the second factor, and with it every enrolment."""
    with op.batch_alter_table("users") as batch:
        batch.drop_column("totp_last_step")
        batch.drop_column("totp_confirmed_at")
        batch.drop_column("totp_secret")
