"""Add `pomodoros.notified_at`.

One nullable column with no server default, which is the only shape SQLite adds
in place. Existing pomodoros read NULL, and that is correct rather than a
backfill problem: every one of them is long past its grace period, so the
scheduler skips them as stale instead of announcing a week of finished focus
blocks the moment this ships.


Revision ID: f6c04b8a7612
Revises: 1ab1280da471
Create Date: 2026-08-21 07:42:16.122720

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6c04b8a7612'
down_revision: Union[str, Sequence[str], None] = '1ab1280da471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.drop_column('notified_at')

    # ### end Alembic commands ###
