"""deduction bands

Revision ID: ff867453dd4f
Revises: 928f0c8bc1a9
Create Date: 2026-08-12 22:10:57.750932

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff867453dd4f'
down_revision: Union[str, Sequence[str], None] = '928f0c8bc1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduction_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('from_minutes', sa.Integer(), nullable=False),
    sa.Column('deduct_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('deduct_minutes >= 0', name='ck_band_deduction_positive'),
    sa.CheckConstraint('from_minutes >= 0', name='ck_band_threshold_positive'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'from_minutes', name='uq_band_threshold')
    )
    with op.batch_alter_table('deduction_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deduction_bands_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deduction_bands_tag_id'))

    op.drop_table('deduction_bands')
    # ### end Alembic commands ###
