import { offsetLabel } from '../clock.js'
import { dayOffsets, slices, startingDay } from './duration.js'

/**
 * The totals `/api/time/summary` returns, worked out here.
 *
 * A second implementation of rules the server owns, which the codebase
 * otherwise refuses to have — and the reason is the one thing the offline
 * feature cannot buy any other way: with no connection there is no server to
 * ask, and a record that cannot total a day is not a record.
 *
 * What keeps the two honest is `summary.test.js`, which runs a corpus of cases
 * through both and fails when they disagree. Neither implementation is allowed
 * to change alone. When one does, the corpus is regenerated by
 * `backend/scripts/dump_derivations.py` and the test says so.
 */

/**
 * Total the time each project holds on each local day.
 *
 * @param {Array<object>} entries Sessions, in any order.
 * @param {number} asOf Milliseconds since the epoch, for a running session.
 * @returns {Record<string, Record<number, number>>} `{day: {project_id: seconds}}`.
 *   Parallel sessions are added, so a day's total across projects can exceed 24
 *   hours — that is what a sum over projects means.
 */
export function summarise(entries, asOf) {
  const offsets = dayOffsets(entries)
  const totals = {}
  for (const entry of entries) {
    for (const part of slices(entry, asOf, offsets)) {
      if (!part.seconds) continue
      const byProject = (totals[part.day] ??= {})
      byProject[entry.project_id] = (byProject[entry.project_id] ?? 0) + part.seconds
    }
  }
  return totals
}

/**
 * Regroup per-project totals under the tags covering those projects.
 *
 * A project carrying two tags counts fully toward both, so the tag numbers
 * overlap: they are the same time from another angle, not a partition of it.
 *
 * @param {Record<string, Record<number, number>>} totals As `summarise` returns.
 * @param {Record<number, Array<number>>} tagsOf `{project_id: [tag_id, …]}`. A
 *   project absent, or present with no tags, is untagged.
 * @returns {Record<string, Record<string, number>>} `{day: {tag_id: seconds}}`,
 *   with the key `null` for untagged work so every tracked second is accounted
 *   for.
 */
export function groupByTag(totals, tagsOf) {
  const grouped = {}
  for (const [day, byProject] of Object.entries(totals)) {
    const bucket = (grouped[day] ??= {})
    for (const [projectId, seconds] of Object.entries(byProject)) {
      const keys = tagsOf[projectId]?.length ? tagsOf[projectId] : [null]
      for (const key of keys) bucket[key] = (bucket[key] ?? 0) + seconds
    }
  }
  return grouped
}

/**
 * The deduction a day of this length attracts, in seconds.
 *
 * The highest threshold the day reaches applies, and the deduction never takes
 * the day below zero — ten minutes tracked minus a thirty minute break is
 * nothing, not minus twenty. A band with no `deduct_minutes` caps instead: it
 * removes whatever the day ran past its threshold.
 *
 * @param {number} trackedSeconds What was tracked on the day, for one tag.
 * @param {Array<{from_minutes: number, deduct_minutes: number|null}>} bands The
 *   tag's rule, in any order.
 * @returns {number} Seconds to remove. Zero when nothing was tracked: a day off
 *   owes no lunch break.
 */
export function deductionFor(trackedSeconds, bands) {
  if (trackedSeconds <= 0 || !bands?.length) return 0
  const reached = bands.filter((band) => band.from_minutes * 60 <= trackedSeconds)
  if (!reached.length) return 0
  const band = reached.reduce((held, one) =>
    one.from_minutes > held.from_minutes ? one : held
  )
  if (band.deduct_minutes === null || band.deduct_minutes === undefined) {
    return trackedSeconds - band.from_minutes * 60
  }
  return Math.min(trackedSeconds, band.deduct_minutes * 60)
}

/**
 * The time a tag's rule adds to a day, in seconds.
 *
 * A flat amount on any day the tag tracked anything, with no minimum. Zero on a
 * day that tracked nothing — the mirror of a day off owing no lunch break.
 *
 * @param {number} trackedSeconds
 * @param {number|null} addMinutes The tag's addition, or null for none.
 * @returns {number} Seconds to add.
 */
export function addedFor(trackedSeconds, addMinutes) {
  if (trackedSeconds <= 0 || !addMinutes) return 0
  return addMinutes * 60
}

/**
 * What a day reports after its tag's whole rule.
 *
 * The addition lands **first**, and the bands are then tested against the
 * increased total. That ordering is the rule: three hours does not reach a
 * three-and-a-half hour threshold, three hours plus an added one does, so the
 * same band applies in one case and not the other.
 *
 * @param {number} trackedSeconds
 * @param {Array<object>} bands
 * @param {number|null} addMinutes
 * @returns {number} What the day reports, never below zero.
 */
export function reportedFor(trackedSeconds, bands, addMinutes = null) {
  const total = trackedSeconds + addedFor(trackedSeconds, addMinutes)
  return total - deductionFor(total, bands)
}

/**
 * Build the rows `/api/time/summary` would return.
 *
 * The shape matters as much as the numbers: this stands in for the endpoint
 * when there is nothing to ask, so what it hands back has to be what the pages
 * already read — one row per day and group, sorted the same way.
 *
 * @param {{entries: Array<object>, asOf: number, by: string,
 *   tagsOf?: Record<number, Array<number>>,
 *   rulesOf?: Record<string, {add_minutes: number|null, bands: Array<object>}>,
 *   start?: string, end?: string}} input
 * @returns {Array<{day: string, key: number|null, seconds: number,
 *   deduction: number, reported: number}>}
 */
export function summaryRows({ entries, asOf, by, tagsOf = {}, rulesOf = {}, start, end }) {
  const totals = summarise(entries, asOf)
  const grouped = by === 'tag' ? groupByTag(totals, tagsOf) : totals

  const rows = []
  for (const day of Object.keys(grouped).toSorted()) {
    if (start && day < start) continue
    if (end && day > end) continue
    const bucket = grouped[day]
    // Untagged last, then by key, which is the order the server sorts in: a
    // page that draws them in order would otherwise disagree with itself the
    // moment it went offline.
    const keys = Object.keys(bucket).toSorted((a, b) => {
      if (a === 'null') return 1
      if (b === 'null') return -1
      return Number(a) - Number(b)
    })
    for (const key of keys) {
      const seconds = bucket[key]
      // Only a tag carries a rule. A project row, and the untagged bucket,
      // report exactly what they tracked.
      const rule = by === 'tag' ? rulesOf[key] : undefined
      const bands = rule?.bands ?? []
      const add = rule?.add_minutes ?? null
      const added = addedFor(seconds, add)
      rows.push({
        day,
        key: key === 'null' ? null : Number(key),
        seconds,
        added,
        // Measured against the increased total, which is what the rule deducts
        // from — reporting the deduction against `seconds` would give a number
        // that does not reconcile with `reported`.
        deduction: deductionFor(seconds + added, bands),
        reported: reportedFor(seconds, bands, add),
      })
    }
  }
  return rows
}

/** The first and last local day any of these sessions belongs to. */
export function trackedEdges(entries) {
  if (!entries.length) return { first: null, last: null }
  const days = entries.map((entry) => startingDay(entry)).toSorted()
  return { first: days[0], last: days.at(-1) }
}

/**
 * The three tables the time export holds, as CSV rows.
 *
 * Built from the same functions the record and the patterns draw from, which is
 * the point: the file and the screen are no longer two implementations that
 * have to be kept in step, they are one.
 *
 * @param {{entries: Array<object>, projects: Array<object>, tags: Array<object>,
 *   rulesOf: Record<string, {add_minutes: number|null, bands: Array<object>}>,
 *   asOf: number}} input
 * @returns {Record<string, Array<Array<unknown>>>} Rows by file name.
 */
export function exportTables({ entries, projects, tags, rulesOf, asOf }) {
  const named = new Map(projects.map((project) => [project.id, project]))
  const tagNames = new Map(tags.map((tag) => [tag.id, tag.name]))
  const offsets = dayOffsets(entries)

  // Local first, because that is the reading every other view shows; UTC is
  // kept beside it so a session stays unambiguous once exported, and the offset
  // is spelled out rather than left to be inferred from the pair.
  const sessions = [
    [
      'Project',
      'Started',
      'Ended',
      'Day offset',
      'Recorded offset',
      'Started (UTC)',
      'Ended (UTC)',
      'Hours',
      'Note',
    ],
  ]
  for (const entry of entries.toSorted((a, b) => (a.started_at < b.started_at ? -1 : 1))) {
    const held = offsets[startingDay(entry)] ?? entry.utc_offset
    const seconds = slices(entry, asOf, offsets).reduce((sum, part) => sum + part.seconds, 0)
    sessions.push([
      named.get(entry.project_id)?.name ?? '',
      localStamp(entry.started_at, held),
      entry.ended_at ? localStamp(entry.ended_at, held) : 'running',
      offsetLabel(held),
      offsetLabel(entry.utc_offset),
      entry.started_at.slice(0, 16).replace('T', ' '),
      entry.ended_at ? entry.ended_at.slice(0, 16).replace('T', ' ') : 'running',
      Math.round((seconds / 3600) * 100) / 100,
      entry.note ?? '',
    ])
  }

  const live = new Set(projects.filter((project) => project.active).map((p) => p.id))
  const tracked = entries.filter((entry) => live.has(entry.project_id))
  const tagsOf = Object.fromEntries(
    projects.map((project) => [project.id, project.tags.map((tag) => tag.id)])
  )

  const grouped = (by) => {
    const rows = [['Day', by === 'tag' ? 'Tag' : 'Project', 'Hours']]
    for (const row of summaryRows({ entries: tracked, asOf, by, tagsOf, rulesOf })) {
      const name =
        by === 'tag'
          ? (row.key === null ? 'Untagged' : (tagNames.get(row.key) ?? ''))
          : (named.get(row.key)?.name ?? '')
      // `reported`, not `seconds`: a tag with a lunch rule reports the hours it
      // reports, and the export is the one place a second, un-deducted figure
      // would be hardest to notice was the wrong one.
      rows.push([row.day, name, Math.round((row.reported / 3600) * 100) / 100])
    }
    return rows
  }

  return {
    'sessions.csv': sessions,
    'by-project.csv': grouped('project'),
    'by-tag.csv': grouped('tag'),
  }
}

/** `YYYY-MM-DD HH:MM` in a session's own offset. */
function localStamp(instant, offsetMinutes) {
  return new Date(Date.parse(`${instant}Z`) + offsetMinutes * 60_000)
    .toISOString()
    .slice(0, 16)
    .replace('T', ' ')
}
